// <auto-generated />
using System;
using Bank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20240602114508_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank.Models.Клиент", b =>
                {
                    b.Property<int>("ID_Клиента")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Клиента"));

                    b.Property<int>("ID_Отделения")
                        .HasColumnType("int");

                    b.Property<string>("Адрес")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ДатаРождения")
                        .HasColumnType("datetime2");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ЭлектроннаяПочта")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Клиента");

                    b.ToTable("Клиенты");
                });

            modelBuilder.Entity("Bank.Models.Кредит", b =>
                {
                    b.Property<int>("ID_Кредита")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Кредита"));

                    b.Property<int>("ID_Клиента")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаНачала")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ДатаОкончания")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ОсновнаяСумма")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ПроцентнаяСтавка")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ТипКредита")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Кредита");

                    b.ToTable("Кредиты");
                });

            modelBuilder.Entity("Bank.Models.ОтделениеБанка", b =>
                {
                    b.Property<int>("ID_Отделения")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Отделения"));

                    b.Property<int>("ID_Сотрудника")
                        .HasColumnType("int");

                    b.Property<string>("Адрес")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("НазваниеОтделения")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("НомерТелефона")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Отделения");

                    b.ToTable("ОтделенияБанков");
                });

            modelBuilder.Entity("Bank.Models.ПлатежПоКредиту", b =>
                {
                    b.Property<int>("ID_Платежа")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Платежа"));

                    b.Property<int>("ID_Кредита")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаПлатежа")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("СуммаПлатежа")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Платежа");

                    b.ToTable("ПлатежиПоКредитам");
                });

            modelBuilder.Entity("Bank.Models.Сотрудник", b =>
                {
                    b.Property<int>("ID_Сотрудника")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Сотрудника"));

                    b.Property<DateTime>("ДатаНаима")
                        .HasColumnType("datetime2");

                    b.Property<string>("Должность")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("НомерТелефона")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ЭлектроннаяПочта")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Сотрудника");

                    b.ToTable("Сотрудники");
                });

            modelBuilder.Entity("Bank.Models.Счет", b =>
                {
                    b.Property<int>("ID_Счета")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Счета"));

                    b.Property<int>("ID_Клиента")
                        .HasColumnType("int");

                    b.Property<decimal>("Баланс")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ДатаСоздания")
                        .HasColumnType("datetime2");

                    b.Property<string>("ТипСчета")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Счета");

                    b.ToTable("Счета");
                });

            modelBuilder.Entity("Bank.Models.Транзакция", b =>
                {
                    b.Property<int>("ID_Транзакции")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Транзакции"));

                    b.Property<int>("ID_Счета")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаТранзакции")
                        .HasColumnType("datetime2");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Сумма")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ТипТранзакции")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Транзакции");

                    b.ToTable("Транзакции");
                });
#pragma warning restore 612, 618
        }
    }
}
